export const enum Status {
  IDLE = 'idle',
  PENDING = 'pending',
  CHECKED = 'checked',
  LOADING = 'loading',
  LOADING_MORE = 'loadingMore',
  FAILED = 'failed',
  FAILED_MORE = 'failedMore',
  DISABLED = 'disabled',
  SUCCEEDED = 'succeeded',
  FINAL = 'final',
  CREATING = 'creating',
  DELETING = 'deleting',
  RESETTING = 'resetting',
  SAVING = 'saving',
  VIEWING = 'viewing',
  LEARNED = 'learned',
  UNLEARNED = 'unlearned',
  SAVING_WITH_EXIT = 'savingWithExit',
  COMPLETING = 'completing',
  NOT_FOUND = 'not_found',
  EMPTY = 'empty',
  FOUND = 'found',
  OK = 'ok'
}